<a href="https://colab.research.google.com/github/foxstar69/jovian.ai/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('15HpQEAw73i1NqtJ7fGmjj7yRDiqtMFk7')

# Assingment 1

fuction i chose for this assingment are randmoly picked from the documentation.

- mean()
- cos()
- sinh()
- atan()
- ones_like()

Before we begin, let's install and import PyTorch

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.mean()

it takes array asa an input and by using the function we can find the mean of the array.

In [3]:
# Example 1 - working 
a=torch.tensor([[1, 2], [3, 4.],[2,6]])
torch.mean(a)

tensor(3.)

Ive taken a array and assinged it to a variable "a" then called the fuction mean()

In [4]:
# Example 2 - working
b=torch.randn(4,6)
torch.mean(b)

tensor(-0.0293)

instead of taking array manually i have used randn() to generate an array and founbd the mean of it.

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
c=torch.tensor([[1, 2,0], [3, 4.]])
torch.mean(c)

ValueError: ignored

there is an error generated here beacause the size of the array is not correct 

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [6]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 71kB 3.3MB/s 


In [7]:
import jovian

In [10]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirudh90hyd/01-tensor-operations


'https://jovian.ai/anirudh90hyd/01-tensor-operations'

## Function 2 - cos()

it is a trigonometric function used to obtain cosine of an expression

In [16]:
# Example 1 - working
a=torch.tensor([[1.34,5.345,8.654,6.34]])
torch.cos(a)


tensor([[ 0.2288,  0.5913, -0.7174,  0.9984]])

for finding out cosine of a values  we need to make sure that all the values are in vector form

In [18]:
# Example 2 - working
b=torch.randn(5)
torch.cos(b)

tensor([0.9687, 0.9300, 0.9271, 0.5356, 0.8804])

here ive generated randam vectors

In [19]:
# Example 3 - error
c=torch.tensor([[2,4],[6,7],[5,3]])
torch.cos(c)

RuntimeError: ignored

Explanation about example

Closing comments about when to use this function

In [20]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirudh90hyd/01-tensor-operations


'https://jovian.ai/anirudh90hyd/01-tensor-operations'

## Function 3 - atai

Returns a new tensor with the arctangent of the elements of input.

In [24]:
# Example 1 - working
a=torch.tensor([[1.34,5.345,8.654,6.34]])
torch.atan(a)

tensor([[0.9297, 1.3858, 1.4558, 1.4144]])

Explanation about example

In [25]:
# Example 2 - working
b=torch.randn(5)
torch.atan(b)

tensor([ 0.3194,  0.7638, -0.6564, -0.5694,  0.0799])

Explanation about example

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
c=torch.tensor([[2,4],[6,7],[5,3]])
torch.atan(c)

RuntimeError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - sinh()

it returns a new tensor with the hyperbolic sine of the elements of input.

In [21]:
# Example 1 - working
a=torch.tensor([[1.34,5.345,8.654,6.34]])
torch.sinh(a)

tensor([[1.7786e+00, 1.0478e+02, 2.8665e+03, 2.8340e+02]])

Explanation about example

In [22]:
# Example 2 - working
b=torch.randn(5)
torch.sinh(b)

tensor([-1.2415, -0.0450, -1.4455,  0.5506, -0.6139])

Explanation about example

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
c=torch.tensor([[2,4],[6,7],[5,3]])
torch.sinh(c)

RuntimeError: ignored

Explanation about example

Closing comments about when to use this function

In [27]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirudh90hyd/01-tensor-operations


'https://jovian.ai/anirudh90hyd/01-tensor-operations'

## Function 5 - one_like

in this function a given tensor is gfilled with a scalar value with a same size of input.

In [28]:
# Example 1 - working
a=torch.tensor([[1.34,5.345,8.654,6.34]])
torch.ones_like(a)

tensor([[1., 1., 1., 1.]])

Explanation about example

In [ ]:
# Example 2 - working
b=torch.randn(5)
torch.ones_like(b)

Explanation about example

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
c=torch.tensor([[2,4],[6,7],[5],])
torch.ones_like(c)

ValueError: ignored

Explanation about example

Closing comments about when to use this function

In [32]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirudh90hyd/01-tensor-operations


'https://jovian.ai/anirudh90hyd/01-tensor-operations'

## Conclusion
This notebook covers various fucntions in  tensor and its operation and use. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* cos function(): https://www.geeksforgeeks.org/python-pytorch-cos-method/#:~:text=cos()%20provides%20support%20for,element%2Dwise%20cosine%20is%20computed.&text=Return%20type%3A%20A%20tensor%20with,type%20as%20that%20of%20x.


In [34]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirudh90hyd/01-tensor-operations


'https://jovian.ai/anirudh90hyd/01-tensor-operations'